site_name: ntloss
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
nav:
  - Home: index.md
  - API:
      - ntloss: reference/ntloss.md
