name: Pytest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install uv
      run: python -m pip install --upgrade uv

    - name: Install project & dev dependencies
      run: |
        uv sync

    - name: Run Ruff
      env:
        PYTHONPATH: .
      run: uv run ruff check ntloss tests

    - name: Run mypy
      env:
        PYTHONPATH: .
      run: uv run mypy -p ntloss

    - name: Run Pytest
      env:
        PYTHONPATH: .
      run: uv run pytest -svx ./tests